version: '3.8'

services:
  tftp-server:
    image: ghcr.io/tomthelegend23/hhs-tropometrics-tftp:latest
    container_name: tftp-server
    network_mode: host
    volumes:
      - ./NetConfigs:/var/tftpboot
    environment:
      - TFTP_ADDRESS=0.0.0.0:69
      - TFTP_OPTIONS=--secure --create --verbose
    restart: unless-stopped